### ISSUE TITLE
Bundle bin/console.php?

### ISSUE THREAD

**Issue by compwright** [pmjones/AutoShell#5]
Re: this example:

```php
/** @var Psr\Container\ContainerInterface $container */

$console = Console::new(
    namespace: 'Sapi\Cli\Command',
    directory: dirname(__DIR__) . '/src/Sapi/Cli/Command',
    factory: fn (string $class) => $container->get($class)
);
```

This appears to be the recommended use case, and it is just about generic enough to be bundled in the project.

Doing this would mean:

* Taking the opinionated position that all commands should be in the `Sapi\Cli\Command` namespace, and no other
* Implementing some discovery or way to configure which `ContainerInterface` implementation to use in a given project

Thoughts?

**Comment by pmjones** [comment]
Console::new(), for its simplicity, is remarkably flexible in what it will let you do in your own projects.

> Taking the opinionated position that all commands should be in the Sapi\Cli\Command namespace, and no other

That one is probably a deal-breaker -- there are too many different ideas about "correct" CLI command structures to force that point.

> Implementing some discovery or way to configure which ContainerInterface implementation to use in a given project

I think it'd be easy enough for Console instantiation code to tell the Console directly what the factory mechanism is, rather than adding discovery logic to AutoShell.

Response/rebuttal?

**Comment by compwright** [comment]
Sure, and you wouldn’t have to use the bundled runner script. But it would
still be nice to have something bundled for a standard (encouraged) use
case.

Sent via Superhuman iOS ***@***.***>
